<?php

namespace Database\Seeders;

use App\Models\Alternatives;
use App\Models\criterias;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EvaluationsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $alternatives = Alternatives::all('id');
        $criterias = criterias::all('id');
        $data = [
            ['alternatives_id' => $alternatives[0]->id, 'criterias_id' => $criterias[0]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[0]->id, 'criterias_id' => $criterias[1]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[0]->id, 'criterias_id' => $criterias[2]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[0]->id, 'criterias_id' => $criterias[3]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[0]->id, 'criterias_id' => $criterias[4]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[0]->id, 'criterias_id' => $criterias[5]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[0]->id, 'criterias_id' => $criterias[6]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[0]->id, 'criterias_id' => $criterias[7]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[1]->id, 'criterias_id' => $criterias[0]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[1]->id, 'criterias_id' => $criterias[1]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[1]->id, 'criterias_id' => $criterias[2]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[1]->id, 'criterias_id' => $criterias[3]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[1]->id, 'criterias_id' => $criterias[4]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[1]->id, 'criterias_id' => $criterias[5]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[1]->id, 'criterias_id' => $criterias[6]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[1]->id, 'criterias_id' => $criterias[7]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[2]->id, 'criterias_id' => $criterias[0]->id, 'value' => 4],
            ['alternatives_id' => $alternatives[2]->id, 'criterias_id' => $criterias[1]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[2]->id, 'criterias_id' => $criterias[2]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[2]->id, 'criterias_id' => $criterias[3]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[2]->id, 'criterias_id' => $criterias[4]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[2]->id, 'criterias_id' => $criterias[5]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[2]->id, 'criterias_id' => $criterias[6]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[2]->id, 'criterias_id' => $criterias[7]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[3]->id, 'criterias_id' => $criterias[0]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[3]->id, 'criterias_id' => $criterias[1]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[3]->id, 'criterias_id' => $criterias[2]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[3]->id, 'criterias_id' => $criterias[3]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[3]->id, 'criterias_id' => $criterias[4]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[3]->id, 'criterias_id' => $criterias[5]->id, 'value' => 4],
            ['alternatives_id' => $alternatives[3]->id, 'criterias_id' => $criterias[6]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[3]->id, 'criterias_id' => $criterias[7]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[4]->id, 'criterias_id' => $criterias[0]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[4]->id, 'criterias_id' => $criterias[1]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[4]->id, 'criterias_id' => $criterias[2]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[4]->id, 'criterias_id' => $criterias[3]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[4]->id, 'criterias_id' => $criterias[4]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[4]->id, 'criterias_id' => $criterias[5]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[4]->id, 'criterias_id' => $criterias[6]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[4]->id, 'criterias_id' => $criterias[7]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[5]->id, 'criterias_id' => $criterias[0]->id, 'value' => 4],
            ['alternatives_id' => $alternatives[5]->id, 'criterias_id' => $criterias[1]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[5]->id, 'criterias_id' => $criterias[2]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[5]->id, 'criterias_id' => $criterias[3]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[5]->id, 'criterias_id' => $criterias[4]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[5]->id, 'criterias_id' => $criterias[5]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[5]->id, 'criterias_id' => $criterias[6]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[5]->id, 'criterias_id' => $criterias[7]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[6]->id, 'criterias_id' => $criterias[0]->id, 'value' => 4],
            ['alternatives_id' => $alternatives[6]->id, 'criterias_id' => $criterias[1]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[6]->id, 'criterias_id' => $criterias[2]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[6]->id, 'criterias_id' => $criterias[3]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[6]->id, 'criterias_id' => $criterias[4]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[6]->id, 'criterias_id' => $criterias[5]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[6]->id, 'criterias_id' => $criterias[6]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[6]->id, 'criterias_id' => $criterias[7]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[7]->id, 'criterias_id' => $criterias[0]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[7]->id, 'criterias_id' => $criterias[1]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[7]->id, 'criterias_id' => $criterias[2]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[7]->id, 'criterias_id' => $criterias[3]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[7]->id, 'criterias_id' => $criterias[4]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[7]->id, 'criterias_id' => $criterias[5]->id, 'value' => 4],
            ['alternatives_id' => $alternatives[7]->id, 'criterias_id' => $criterias[6]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[7]->id, 'criterias_id' => $criterias[7]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[8]->id, 'criterias_id' => $criterias[0]->id, 'value' => 5],
            ['alternatives_id' => $alternatives[8]->id, 'criterias_id' => $criterias[1]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[8]->id, 'criterias_id' => $criterias[2]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[8]->id, 'criterias_id' => $criterias[3]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[8]->id, 'criterias_id' => $criterias[4]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[8]->id, 'criterias_id' => $criterias[5]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[8]->id, 'criterias_id' => $criterias[6]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[8]->id, 'criterias_id' => $criterias[7]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[9]->id, 'criterias_id' => $criterias[0]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[9]->id, 'criterias_id' => $criterias[1]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[9]->id, 'criterias_id' => $criterias[2]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[9]->id, 'criterias_id' => $criterias[3]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[9]->id, 'criterias_id' => $criterias[4]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[9]->id, 'criterias_id' => $criterias[5]->id, 'value' => 4],
            ['alternatives_id' => $alternatives[9]->id, 'criterias_id' => $criterias[6]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[9]->id, 'criterias_id' => $criterias[7]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[10]->id, 'criterias_id' => $criterias[0]->id, 'value' => 5],
            ['alternatives_id' => $alternatives[10]->id, 'criterias_id' => $criterias[1]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[10]->id, 'criterias_id' => $criterias[2]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[10]->id, 'criterias_id' => $criterias[3]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[10]->id, 'criterias_id' => $criterias[4]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[10]->id, 'criterias_id' => $criterias[5]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[10]->id, 'criterias_id' => $criterias[6]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[10]->id, 'criterias_id' => $criterias[7]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[11]->id, 'criterias_id' => $criterias[0]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[11]->id, 'criterias_id' => $criterias[1]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[11]->id, 'criterias_id' => $criterias[2]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[11]->id, 'criterias_id' => $criterias[3]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[11]->id, 'criterias_id' => $criterias[4]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[11]->id, 'criterias_id' => $criterias[5]->id, 'value' => 4],
            ['alternatives_id' => $alternatives[11]->id, 'criterias_id' => $criterias[6]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[11]->id, 'criterias_id' => $criterias[7]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[12]->id, 'criterias_id' => $criterias[0]->id, 'value' => 4],
            ['alternatives_id' => $alternatives[12]->id, 'criterias_id' => $criterias[1]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[12]->id, 'criterias_id' => $criterias[2]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[12]->id, 'criterias_id' => $criterias[3]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[12]->id, 'criterias_id' => $criterias[4]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[12]->id, 'criterias_id' => $criterias[5]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[12]->id, 'criterias_id' => $criterias[6]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[12]->id, 'criterias_id' => $criterias[7]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[13]->id, 'criterias_id' => $criterias[0]->id, 'value' => 4],
            ['alternatives_id' => $alternatives[13]->id, 'criterias_id' => $criterias[1]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[13]->id, 'criterias_id' => $criterias[2]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[13]->id, 'criterias_id' => $criterias[3]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[13]->id, 'criterias_id' => $criterias[4]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[13]->id, 'criterias_id' => $criterias[5]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[13]->id, 'criterias_id' => $criterias[6]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[13]->id, 'criterias_id' => $criterias[7]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[14]->id, 'criterias_id' => $criterias[0]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[14]->id, 'criterias_id' => $criterias[1]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[14]->id, 'criterias_id' => $criterias[2]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[14]->id, 'criterias_id' => $criterias[3]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[14]->id, 'criterias_id' => $criterias[4]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[14]->id, 'criterias_id' => $criterias[5]->id, 'value' => 4],
            ['alternatives_id' => $alternatives[14]->id, 'criterias_id' => $criterias[6]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[14]->id, 'criterias_id' => $criterias[7]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[15]->id, 'criterias_id' => $criterias[0]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[15]->id, 'criterias_id' => $criterias[1]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[15]->id, 'criterias_id' => $criterias[2]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[15]->id, 'criterias_id' => $criterias[3]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[15]->id, 'criterias_id' => $criterias[4]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[15]->id, 'criterias_id' => $criterias[5]->id, 'value' => 4],
            ['alternatives_id' => $alternatives[15]->id, 'criterias_id' => $criterias[6]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[15]->id, 'criterias_id' => $criterias[7]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[16]->id, 'criterias_id' => $criterias[0]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[16]->id, 'criterias_id' => $criterias[1]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[16]->id, 'criterias_id' => $criterias[2]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[16]->id, 'criterias_id' => $criterias[3]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[16]->id, 'criterias_id' => $criterias[4]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[16]->id, 'criterias_id' => $criterias[5]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[16]->id, 'criterias_id' => $criterias[6]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[16]->id, 'criterias_id' => $criterias[7]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[17]->id, 'criterias_id' => $criterias[0]->id, 'value' => 5],
            ['alternatives_id' => $alternatives[17]->id, 'criterias_id' => $criterias[1]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[17]->id, 'criterias_id' => $criterias[2]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[17]->id, 'criterias_id' => $criterias[3]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[17]->id, 'criterias_id' => $criterias[4]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[17]->id, 'criterias_id' => $criterias[5]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[17]->id, 'criterias_id' => $criterias[6]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[17]->id, 'criterias_id' => $criterias[7]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[18]->id, 'criterias_id' => $criterias[0]->id, 'value' => 4],
            ['alternatives_id' => $alternatives[18]->id, 'criterias_id' => $criterias[1]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[18]->id, 'criterias_id' => $criterias[2]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[18]->id, 'criterias_id' => $criterias[3]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[18]->id, 'criterias_id' => $criterias[4]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[18]->id, 'criterias_id' => $criterias[5]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[18]->id, 'criterias_id' => $criterias[6]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[18]->id, 'criterias_id' => $criterias[7]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[19]->id, 'criterias_id' => $criterias[0]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[19]->id, 'criterias_id' => $criterias[1]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[19]->id, 'criterias_id' => $criterias[2]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[19]->id, 'criterias_id' => $criterias[3]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[19]->id, 'criterias_id' => $criterias[4]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[19]->id, 'criterias_id' => $criterias[5]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[19]->id, 'criterias_id' => $criterias[6]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[19]->id, 'criterias_id' => $criterias[7]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[20]->id, 'criterias_id' => $criterias[0]->id, 'value' => 4],
            ['alternatives_id' => $alternatives[20]->id, 'criterias_id' => $criterias[1]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[20]->id, 'criterias_id' => $criterias[2]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[20]->id, 'criterias_id' => $criterias[3]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[20]->id, 'criterias_id' => $criterias[4]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[20]->id, 'criterias_id' => $criterias[5]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[20]->id, 'criterias_id' => $criterias[6]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[20]->id, 'criterias_id' => $criterias[7]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[21]->id, 'criterias_id' => $criterias[0]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[21]->id, 'criterias_id' => $criterias[1]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[21]->id, 'criterias_id' => $criterias[2]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[21]->id, 'criterias_id' => $criterias[3]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[21]->id, 'criterias_id' => $criterias[4]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[21]->id, 'criterias_id' => $criterias[5]->id, 'value' => 4],
            ['alternatives_id' => $alternatives[21]->id, 'criterias_id' => $criterias[6]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[21]->id, 'criterias_id' => $criterias[7]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[22]->id, 'criterias_id' => $criterias[0]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[22]->id, 'criterias_id' => $criterias[1]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[22]->id, 'criterias_id' => $criterias[2]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[22]->id, 'criterias_id' => $criterias[3]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[22]->id, 'criterias_id' => $criterias[4]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[22]->id, 'criterias_id' => $criterias[5]->id, 'value' => 4],
            ['alternatives_id' => $alternatives[22]->id, 'criterias_id' => $criterias[6]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[22]->id, 'criterias_id' => $criterias[7]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[23]->id, 'criterias_id' => $criterias[0]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[23]->id, 'criterias_id' => $criterias[1]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[23]->id, 'criterias_id' => $criterias[2]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[23]->id, 'criterias_id' => $criterias[3]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[23]->id, 'criterias_id' => $criterias[4]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[23]->id, 'criterias_id' => $criterias[5]->id, 'value' => 4],
            ['alternatives_id' => $alternatives[23]->id, 'criterias_id' => $criterias[6]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[23]->id, 'criterias_id' => $criterias[7]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[24]->id, 'criterias_id' => $criterias[0]->id, 'value' => 4],
            ['alternatives_id' => $alternatives[24]->id, 'criterias_id' => $criterias[1]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[24]->id, 'criterias_id' => $criterias[2]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[24]->id, 'criterias_id' => $criterias[3]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[24]->id, 'criterias_id' => $criterias[4]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[24]->id, 'criterias_id' => $criterias[5]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[24]->id, 'criterias_id' => $criterias[6]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[24]->id, 'criterias_id' => $criterias[7]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[25]->id, 'criterias_id' => $criterias[0]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[25]->id, 'criterias_id' => $criterias[1]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[25]->id, 'criterias_id' => $criterias[2]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[25]->id, 'criterias_id' => $criterias[3]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[25]->id, 'criterias_id' => $criterias[4]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[25]->id, 'criterias_id' => $criterias[5]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[25]->id, 'criterias_id' => $criterias[6]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[25]->id, 'criterias_id' => $criterias[7]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[26]->id, 'criterias_id' => $criterias[0]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[26]->id, 'criterias_id' => $criterias[1]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[26]->id, 'criterias_id' => $criterias[2]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[26]->id, 'criterias_id' => $criterias[3]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[26]->id, 'criterias_id' => $criterias[4]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[26]->id, 'criterias_id' => $criterias[5]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[26]->id, 'criterias_id' => $criterias[6]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[26]->id, 'criterias_id' => $criterias[7]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[27]->id, 'criterias_id' => $criterias[0]->id, 'value' => 4],
            ['alternatives_id' => $alternatives[27]->id, 'criterias_id' => $criterias[1]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[27]->id, 'criterias_id' => $criterias[2]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[27]->id, 'criterias_id' => $criterias[3]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[27]->id, 'criterias_id' => $criterias[4]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[27]->id, 'criterias_id' => $criterias[5]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[27]->id, 'criterias_id' => $criterias[6]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[27]->id, 'criterias_id' => $criterias[7]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[28]->id, 'criterias_id' => $criterias[0]->id, 'value' => 4],
            ['alternatives_id' => $alternatives[28]->id, 'criterias_id' => $criterias[1]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[28]->id, 'criterias_id' => $criterias[2]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[28]->id, 'criterias_id' => $criterias[3]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[28]->id, 'criterias_id' => $criterias[4]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[28]->id, 'criterias_id' => $criterias[5]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[28]->id, 'criterias_id' => $criterias[6]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[28]->id, 'criterias_id' => $criterias[7]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[29]->id, 'criterias_id' => $criterias[0]->id, 'value' => 4],
            ['alternatives_id' => $alternatives[29]->id, 'criterias_id' => $criterias[1]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[29]->id, 'criterias_id' => $criterias[2]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[29]->id, 'criterias_id' => $criterias[3]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[29]->id, 'criterias_id' => $criterias[4]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[29]->id, 'criterias_id' => $criterias[5]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[29]->id, 'criterias_id' => $criterias[6]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[29]->id, 'criterias_id' => $criterias[7]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[30]->id, 'criterias_id' => $criterias[0]->id, 'value' => 5],
            ['alternatives_id' => $alternatives[30]->id, 'criterias_id' => $criterias[1]->id, 'value' => 2],
            ['alternatives_id' => $alternatives[30]->id, 'criterias_id' => $criterias[2]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[30]->id, 'criterias_id' => $criterias[3]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[30]->id, 'criterias_id' => $criterias[4]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[30]->id, 'criterias_id' => $criterias[5]->id, 'value' => 3],
            ['alternatives_id' => $alternatives[30]->id, 'criterias_id' => $criterias[6]->id, 'value' => 1],
            ['alternatives_id' => $alternatives[30]->id, 'criterias_id' => $criterias[7]->id, 'value' => 3],
            // ['alternatives_id' => $alternatives[31]->id, 'criterias_id' => $criterias[0]->id, 'value' => 3],
            // ['alternatives_id' => $alternatives[31]->id, 'criterias_id' => $criterias[1]->id, 'value' => 2],
            // ['alternatives_id' => $alternatives[31]->id, 'criterias_id' => $criterias[2]->id, 'value' => 1],
            // ['alternatives_id' => $alternatives[31]->id, 'criterias_id' => $criterias[3]->id, 'value' => 2],
            // ['alternatives_id' => $alternatives[31]->id, 'criterias_id' => $criterias[4]->id, 'value' => 3],
            // ['alternatives_id' => $alternatives[31]->id, 'criterias_id' => $criterias[5]->id, 'value' => 3],
            // ['alternatives_id' => $alternatives[31]->id, 'criterias_id' => $criterias[6]->id, 'value' => 2],
            // ['alternatives_id' => $alternatives[31]->id, 'criterias_id' => $criterias[7]->id, 'value' => 3],
            // ['alternatives_id' => $alternatives[32]->id, 'criterias_id' => $criterias[0]->id, 'value' => 2],
            // ['alternatives_id' => $alternatives[32]->id, 'criterias_id' => $criterias[1]->id, 'value' => 1],
            // ['alternatives_id' => $alternatives[32]->id, 'criterias_id' => $criterias[2]->id, 'value' => 3],
            // ['alternatives_id' => $alternatives[32]->id, 'criterias_id' => $criterias[3]->id, 'value' => 1],
            // ['alternatives_id' => $alternatives[32]->id, 'criterias_id' => $criterias[4]->id, 'value' => 1],
            // ['alternatives_id' => $alternatives[32]->id, 'criterias_id' => $criterias[5]->id, 'value' => 3],
            // ['alternatives_id' => $alternatives[32]->id, 'criterias_id' => $criterias[6]->id, 'value' => 3],
            // ['alternatives_id' => $alternatives[32]->id, 'criterias_id' => $criterias[7]->id, 'value' => 3],
            // ['alternatives_id' => $alternatives[33]->id, 'criterias_id' => $criterias[0]->id, 'value' => 5],
            // ['alternatives_id' => $alternatives[33]->id, 'criterias_id' => $criterias[1]->id, 'value' => 1],
            // ['alternatives_id' => $alternatives[33]->id, 'criterias_id' => $criterias[2]->id, 'value' => 2],
            // ['alternatives_id' => $alternatives[33]->id, 'criterias_id' => $criterias[3]->id, 'value' => 1],
            // ['alternatives_id' => $alternatives[33]->id, 'criterias_id' => $criterias[4]->id, 'value' => 3],
            // ['alternatives_id' => $alternatives[33]->id, 'criterias_id' => $criterias[5]->id, 'value' => 3],
            // ['alternatives_id' => $alternatives[33]->id, 'criterias_id' => $criterias[6]->id, 'value' => 3],
            // ['alternatives_id' => $alternatives[33]->id, 'criterias_id' => $criterias[7]->id, 'value' => 1],
            // ['alternatives_id' => $alternatives[34]->id, 'criterias_id' => $criterias[0]->id, 'value' => 2],
            // ['alternatives_id' => $alternatives[34]->id, 'criterias_id' => $criterias[1]->id, 'value' => 3],
            // ['alternatives_id' => $alternatives[34]->id, 'criterias_id' => $criterias[2]->id, 'value' => 2],
            // ['alternatives_id' => $alternatives[34]->id, 'criterias_id' => $criterias[3]->id, 'value' => 1],
            // ['alternatives_id' => $alternatives[34]->id, 'criterias_id' => $criterias[4]->id, 'value' => 2],
            // ['alternatives_id' => $alternatives[34]->id, 'criterias_id' => $criterias[5]->id, 'value' => 3],
            // ['alternatives_id' => $alternatives[34]->id, 'criterias_id' => $criterias[6]->id, 'value' => 3],
            // ['alternatives_id' => $alternatives[34]->id, 'criterias_id' => $criterias[7]->id, 'value' => 2],
        ];

        DB::table('evaluations')->insert($data);
    }
}
